
var questions = [
    "Input two characters and print them on the next line in the reverse order.",
    "Input two characters and swap them without using third variable and print them on the next line.",
    "To find out volume of sphere and area of triangle, given radius as input",
    "To check whether two inputted numbers are same or not",
    "To check whether an input no. is possitive or negative",
    "To check whether an input year is leap year or not",
    "To check whether the input character is uppercase or lowercase",
    "To check whether the input alphabet is vowel or not",
    "To convert an inputted alphabet from upper to lower case and from lower to upper case",
    "To check whether an input no. is even or odd",
    "To input marks of 5 subject, then calculate and print percentage and grade",
    "Take 5 digit no. and print every digit on the next line",
    "To display all numbers from 1 to N",
    "To display the sum of all numbers from 1 to N",
    "To display the product of all numbers from 1 to N",
    "To display the factorial of given integer",
    "To display the squares of all number from 1 to N",
    "Take a number as input and print all of its divisors",
    "To print the no. from 1 to N along with indication whether each is even or odd ",
    "To print the power of A power B using user defined function where A and B are integer input",
    "To display all number from 1 to N and then folloed by N-1 to 1",
    "To calculate the sum of input integer until user input negative no",
    "Take a number and display it in reverse order",
    "Take a five digit number and print the reverse on the next line",
    "To read and display integer array of 10 elements",
    "Take input from user and count and then print total no. of word, vowel and character",
    "To calculate the sum of all number from 1 to N, at the end user will be asked whether to continue or not",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "To display the following pattern",
    "Write a program to input a number N, and then generate the following pattern",

];
